### ISSUE TITLE
关于编译的一些问题，求解答。

### ISSUE THREAD

**Issue by Alexander4731** [zfdx123/build-k40-ksu#15]
1、能告知一下Actions编译出来的KSU及内核版本是多少嘛？
2、看到其他人编译出来的内核（好像是AnyKernel）对于内核有小版本升级，例如（https://www.123pan.com/s/OlEiVv-7BENH.html 提取码8vse），这里面的内核版本为4.19.317，KernelSU版本为11898，想问一下这种是怎么实现的
3、能使用官方内核编译嘛，我最新的澎湃系统1.0.6好像刷了不开机。
4、能不能出一下编译内核的详细教程，只使用过一键脚本编译，还编译失败了，（主要是想自己加入内核的一些特性）

**Comment by zfdx123** [comment]
默认拉取ksu最新新提交，目前ksu已经不再支持菲gki内核
自己维护一个源码仓库或者使用别人维护的小版本更新
官方内核无法使用当前仓库编译，并且需要处理替换自己的boor，或更换内核源代码，或者维护一个ak3
我不确定你所说的特性是什么，本仓库只是为了方便编译使用，使用时填入相关参数即可，如果需要加入自己的东西请手动修改工作流

**Comment by Alexander4731** [comment]
感谢解答！
