### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by clsddy** [zfdx123/build-k40-ksu#16]
![image](https://github.com/user-attachments/assets/a6322b14-603f-4e03-813e-c2ae9a54b1d9)

description: '编译器下载地址'  
        required: false
        type: string
        default: 'https://github.com/XSans0/WeebX-Clang/releases/download/WeebX-Clang-19.0.0git-release/WeebX-Clang-19.0.0git.tar.gz'
已由19.0.0更新为https://github.com/XSans0/WeebX-Clang/releases/download/WeebX-Clang-19.1.5-release/WeebX-Clang-19.1.5.tar.gz

**Comment by zfdx123** [comment]
谢谢

**Comment by clsddy** [comment]
> 谢谢
更新编译器链接是解决第一个编译器链接不存在错误的.
我贴的这个图是编译错误,我看不懂,帮忙看看,谢谢!

**Comment by zfdx123** [comment]
错误不在这，往上找

**Comment by zfdx123** [comment]
`-- KernelSU version: 11996
-- KernelSU Manager signature size: 0x033b
-- KernelSU Manager signature hash: c371061b19d8c7d7d6133c6a9bafe198fa944e50c1b31c9d8daa8d7f1fc2d2d6
  CC      drivers/kernelsu/ksu.o
../drivers/kernelsu/ksu.c:97:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
   97 | MODULE_IMPORT_NS(VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver);
      | ^
      | int
../drivers/kernelsu/ksu.c:97:18: error: a parameter list without types is only allowed in a function definition
   97 | MODULE_IMPORT_NS(VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver);
      |                  ^
2 errors generated.
make[3]: *** [../scripts/Makefile.build:338: drivers/kernelsu/ksu.o] Error 1
make[2]: *** [../scripts/Makefile.build:642: drivers/kernelsu] Error 2
make[1]: *** [/home/runner/work/build-k40-ksu/build-k40-ksu/kernel-source/Makefile:1210: drivers] Error 2
make[1]: *** Waiting for unfinished jobs....`

**Comment by zfdx123** [comment]
run test

**Comment by zfdx123** [comment]
如果卸载模块不能用，就需要修改内核，文档如下 [Umount modules](https://kernelsu.org/guide/how-to-integrate-for-non-gki.html#how-to-backport-path-umount)

**Comment by clsddy** [comment]
谢谢!
