### ISSUE TITLE
请问17.0.8是哪个版本

### ISSUE THREAD

**Issue by clsddy** [zfdx123/build-k40-ksu#4]
k40 miui稳定最后一版不是14.0.7吗

**Comment by zfdx123** [comment]
14.0.8提交的时候写错了

**Comment by zfdx123** [comment]
最新版本是14.0.8

**Comment by clsddy** [comment]
> 最新版本是14.0.8

好的，我以为早就停更了。不好意思

**Comment by clsddy** [comment]
> 最新版本是14.0.8

build完成后，压缩包里有两个镜像，请问另外一个镜像是干啥用的。
Image
new-boot.img

**Comment by zfdx123** [comment]
> > 最新版本是14.0.8
> 
> build完成后，压缩包里有两个镜像，请问另外一个镜像是干啥用的。 Image new-boot.img

image是编译出来的纯内核文件，new-boot就是改好内核的boot，同系统版本可以直接刷

**Comment by clsddy** [comment]
> > > 最新版本是14.0.8
> > 
> > build完成后，压缩包里有两个镜像，请问另外一个镜像是干啥用的。 Image new-boot.img
> 
> image是编译出来的纯内核文件，new-boot就是改好内核的boot，同系统版本可以直接刷

OK，谢谢。请问大佬开的有交流群吗

**Comment by zfdx123** [comment]
> > > > 最新版本是14.0.8
> > > 
> > > 
> > > build完成后，压缩包里有两个镜像，请问另外一个镜像是干啥用的。 Image new-boot.img
> > 
> > 
> > image是编译出来的纯内核文件，new-boot就是改好内核的boot，同系统版本可以直接刷
> 
> OK，谢谢。请问大佬开的有交流群吗


没有也不考虑
