### ISSUE TITLE
配置文件不能自定义设置路径

### ISSUE THREAD

**Issue by 2536** [zfdx123/build-k40-ksu#6]
配置文件的路径只能是/arch/arm64/configs/alioth_defconfig，一旦修改成/arch/arm64/configs/vendor/alioth_defconfig编译就会出错，大佬能不能修复一下？

**Comment by zfdx123** [comment]
我不是很能理解这样改的意义是什么，其次请上传一下错误日志

**Comment by zfdx123** [comment]
已修复
