### ISSUE TITLE
关于BOOT版本和编译其他机型

### ISSUE THREAD

**Issue by 2536** [zfdx123/build-k40-ksu#8]
大佬还有一个问题，如果我有你这个脚本编译别的机型，或者是也是k 40但是系统不是这个miui4.0.8，是不是还要替换boot文件，是不是要替换原机型的boot文件，大佬有q吗？加个q^便联系指导一下

**Comment by zfdx123** [comment]
直接替换成你系统的boot即可，或者直接修改ci，直接打包下来你的内核image，如果要更换内核可以在ci run的时候处理修改为其他的库

**Comment by zfdx123** [comment]
理论来说，不限制机型，内核没问题应该就ok，刚刚测试了一下摆烂内核编译没有问题

**Comment by zfdx123** [comment]
https://github.com/zfdx123/build-k40-ksu/actions/runs/7610656489
